### ISSUE TITLE
the implementation

### ISSUE THREAD

**Issue by chichuhu** [jeason353/IDN#2]
这个模型是不是没有实现完，不应该是3个·结果计算损失吗

**Comment by wk-ff** [comment]
是啊，loss.py里面就是三个结果分别和label计算损失，然后取平均

**Comment by chichuhu** [comment]
看错了，看的model.py文件，应该看models文件夹里的代码

**Comment by chichuhu** [comment]
我看训练的效果还挺好的，就是可惜没有中文数据集

**Comment by WangYingying-hub** [comment]
你好，请问你们都训练了多少个epoch呀，我现在每次的预测结果都是1，好奇怪呀
