### ISSUE TITLE
BHSig260结果

### ISSUE THREAD

**Issue by zhangx10068** [jeason353/IDN#4]
您好！，请问该模型在CEDAR上测试精度是多少？（您复现的结果和论文中的结果一致吗？）
在BHSig260数据集上测试结果有没有异常呀？

**Comment by wk-ff** [comment]
在CEDAR上精度是98.61，比论文里低一点。
在BHSig260上比论文低了6个百分点左右

**Comment by zhangx10068** [comment]
请问在CEDAR数据集上多少轮得到的最佳结果？是直接用源数据集生成对然后用您的模型之间跑就可以吗？因为我看CEDAR数据集org下的图片，明显背景有颜色和forg不同，是需要先进行预处理吗？谢谢

**Comment by wk-ff** [comment]
就训练了几个epoch。我对图片进行了阈值处理（为灰度值设置一个阈值，大于这个阈值的灰度值设为 255，小于这个阈值的灰度值不变），然后resize到相同尺寸。
