### ISSUE TITLE
预处理

### ISSUE THREAD

**Issue by sgdy3** [jeason353/IDN#6]
您好，我注意到预处理部分代码的注释中您写道“要将待处理图像的值除以数据集中图像灰度值的标准差”，但我并没有找到实施部分的代码，而且也没找到论文中相关的去噪处理部分，请问您后续是采用了别种预处理方法吗？

**Comment by wk-ff** [comment]
我没看到这个注释唉，我预处理只是简单做了阈值处理，大于阈值的灰度值设为255，小于等于阈值的灰度值保持不变。同时resize到同一个尺寸

**Comment by sgdy3** [comment]
哦哦，好的，看到您注释部分提到了“normalize each image by dividing the pixel values with the standard deviation of the pixel values of the images in a dataset”，以为存在着相关预处理的步骤。
非常感谢您的回复！
